// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Y2WuoKFMvsqtFKTsXSobT4fdsowX3xk',
    appId: '1:553660421764:web:e5dc7e7d1de628778c54d1',
    messagingSenderId: '553660421764',
    projectId: 'test2-5272d',
    authDomain: 'test2-5272d.firebaseapp.com',
    storageBucket: 'test2-5272d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjqqw90MY-7PTR9_D2Zo6IlXvlRvX9sPk',
    appId: '1:553660421764:android:28799710c1a0982e8c54d1',
    messagingSenderId: '553660421764',
    projectId: 'test2-5272d',
    storageBucket: 'test2-5272d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgmf0fWmu65PMbspltB5D49Eoay0ekcqM',
    appId: '1:553660421764:ios:e93279391e06c77a8c54d1',
    messagingSenderId: '553660421764',
    projectId: 'test2-5272d',
    storageBucket: 'test2-5272d.firebasestorage.app',
    iosBundleId: 'com.example.rebuildedProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgmf0fWmu65PMbspltB5D49Eoay0ekcqM',
    appId: '1:553660421764:ios:e93279391e06c77a8c54d1',
    messagingSenderId: '553660421764',
    projectId: 'test2-5272d',
    storageBucket: 'test2-5272d.firebasestorage.app',
    iosBundleId: 'com.example.rebuildedProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Y2WuoKFMvsqtFKTsXSobT4fdsowX3xk',
    appId: '1:553660421764:web:4acf085d2c7139268c54d1',
    messagingSenderId: '553660421764',
    projectId: 'test2-5272d',
    authDomain: 'test2-5272d.firebaseapp.com',
    storageBucket: 'test2-5272d.firebasestorage.app',
  );
}
